CREATE DATABASE IF NOT EXISTS BANKING;
CREATE SCHEMA IF NOT EXISTS BANKING.RAW;
CREATE SCHEMA IF NOT EXISTS BANKING.ANALYTICS;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE BANKING;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS customer (
    v VARIANT,
    _source_file STRING,
    _loaded_at TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS account (
    v VARIANT,
    _source_file STRING,
    _loaded_at TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS transaction (
    v VARIANT,
    _source_file STRING,
    _loaded_at TIMESTAMP_LTZ
);




