CREATE DATABASE IF NOT EXISTS BANKING;
CREATE SCHEMA IF NOT EXISTS BANKING.RAW;
CREATE SCHEMA IF NOT EXISTS BANKING.ANALYTICS;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE BANKING;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS customer (v VARIANT);
CREATE TABLE IF NOT EXISTS account (v VARIANT);
CREATE TABLE IF NOT EXISTS transaction (v VARIANT);




